# -*- coding: utf-8 -*-
"""live_nav_fetch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IKEU_FvVCQkqPGCN3wED4PbGJ7XBmezW
"""

!pip install pandas numpy matplotlib seaborn plotly sqlalchemy requests scipy jupyter

requirements = """
pandas
numpy
matplotlib
seaborn
plotly
sqlalchemy
requests
scipy
jupyter
"""

with open("requirements.txt", "w") as f:
    f.write(requirements)

print("All dependencies installed successfully!")
print("requirements.txt created.")

import requests
import pandas as pd
from google.colab import drive
import os

drive.mount('/content/drive')

url = "https://api.mfapi.in/mf/125497"

response = requests.get(url)

data = response.json()

"""Extract NAV history data"""

nav_data = data['data']

df = pd.DataFrame(nav_data)

print("First 5 rows:")
print(df.head())

print("\nShape:")
print(df.shape)

"""Saving in Google Drive"""

save_folder = "/content/drive/MyDrive/Bluestock_MF_Datasets"

os.makedirs(save_folder, exist_ok=True)

csv_path = os.path.join(save_folder, "live_nav_hdfc_top100.csv")

df.to_csv(csv_path, index=False)

print(f"\nCSV saved successfully at:\n{csv_path}")

"""SBI Bluechip"""

import requests
import pandas as pd
from google.colab import drive
import os

drive.mount('/content/drive')

url = "https://api.mfapi.in/mf/119551"

response = requests.get(url)

data = response.json()

nav_data = data['data']

df = pd.DataFrame(nav_data)

print("First 5 rows:")
print(df.head())

print("\nShape:")
print(df.shape)


save_folder = "/content/drive/MyDrive/Bluestock_MF_Datasets"

os.makedirs(save_folder, exist_ok=True)

csv_path = os.path.join(save_folder, "live_nav_sbi_bluechip.csv")

df.to_csv(csv_path, index=False)

print(f"\nCSV saved successfully at:\n{csv_path}")

"""ICICI Bluechip"""

url = "https://api.mfapi.in/mf/120503"

response = requests.get(url)

data = response.json()

nav_data = data['data']

df = pd.DataFrame(nav_data)

print("First 5 rows:")
print(df.head())

print("\nShape:")
print(df.shape)


save_folder = "/content/drive/MyDrive/Bluestock_MF_Datasets"

os.makedirs(save_folder, exist_ok=True)

csv_path = os.path.join(save_folder, "live_nav_icici_bluechip.csv")

df.to_csv(csv_path, index=False)

print(f"\nCSV saved successfully at:\n{csv_path}")

"""Nippon Large Cap"""

url = "https://api.mfapi.in/mf/118632"

response = requests.get(url)

data = response.json()

nav_data = data['data']

df = pd.DataFrame(nav_data)

print("First 5 rows:")
print(df.head())

print("\nShape:")
print(df.shape)


save_folder = "/content/drive/MyDrive/Bluestock_MF_Datasets"

os.makedirs(save_folder, exist_ok=True)

csv_path = os.path.join(save_folder, "live_nav_nippon_large_cap.csv")

df.to_csv(csv_path, index=False)

print(f"\nCSV saved successfully at:\n{csv_path}")

"""Axis Bluechip"""

url = "https://api.mfapi.in/mf/119092"

response = requests.get(url)

data = response.json()

nav_data = data['data']

df = pd.DataFrame(nav_data)

print("First 5 rows:")
print(df.head())

print("\nShape:")
print(df.shape)


save_folder = "/content/drive/MyDrive/Bluestock_MF_Datasets"

os.makedirs(save_folder, exist_ok=True)

csv_path = os.path.join(save_folder, "live_nav_axis_bluechip.csv")

df.to_csv(csv_path, index=False)

print(f"\nCSV saved successfully at:\n{csv_path}")

"""Kotak Bluechip"""

url = "https://api.mfapi.in/mf/120841"

response = requests.get(url)

data = response.json()

nav_data = data['data']

df = pd.DataFrame(nav_data)

print("First 5 rows:")
print(df.head())

print("\nShape:")
print(df.shape)


save_folder = "/content/drive/MyDrive/Bluestock_MF_Datasets"

os.makedirs(save_folder, exist_ok=True)

csv_path = os.path.join(save_folder, "live_nav_kotak_bluechip.csv")

df.to_csv(csv_path, index=False)

print(f"\nCSV saved successfully at:\n{csv_path}")