# -*- coding: utf-8 -*-
"""dependencies.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KbdsWWrj7mBAvuRL925JHNmpIm35EVdj

Installing the dependencies
"""

# Install all required libraries in Google Colab

!pip install pandas numpy matplotlib seaborn plotly sqlalchemy requests scipy jupyter

# Create requirements.txt file
requirements = """
pandas
numpy
matplotlib
seaborn
plotly
sqlalchemy
requests
scipy
jupyter
"""

with open("requirements.txt", "w") as f:
    f.write(requirements)

print("All dependencies installed successfully!")
print("requirements.txt created.")

!cat requirements.txt